### ISSUE TITLE
Error EISDIR when 'config' is a directory

### ISSUE THREAD

**Issue by jorrit** [whyleee/nogit#2]
In my project I have a directory `config`. The following code in config.js checks if `config` exists and then proceeds to read it as a file. It doesn't check if `config` is a file, so reading it fails with the EISDIR error.

    readFrom('config', function() {

    fs.exists(configPath, function(exists) {
      if (exists) {
        fs.readFile(configPath, 'utf8', function(err, data) {

**Comment by jorrit** [comment]
I created pull request #3 for this.

**Comment by whyleee** [comment]
`config` file is supposed to be read under `.git` directory (or in the working directory for bare repositories). Could you please provide what exact command fails (eg `bower install`, `npm install` or some manual `nogit` call)?

**Comment by jorrit** [comment]
When I execute `bower install jquery` in a directory that contains a config subdirectory, the command fails. Looking at the code, I can only conclude that it doesn't try to read `./.git/config` but `./config`. But maybe I am missing something.

**Comment by whyleee** [comment]
Thanks. Yep, `nogit` should read `.git/config` file for not bare git repos. I'll take a look at this later today and will also change `exists` to `readFile` error check.

**Comment by whyleee** [comment]
I published new version to npm and nuget.
