### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by Owemeone** [whyleee/nogit#5]
When trying to clone a repo I get the following error:

\node_modules\nogit\node_modules\git-node\node_modules\git-net\smart-http.js:191
          if (line.trim() !== '# service=git-upload-pack') {
                  ^
TypeError: Cannot read property 'trim' of undefined
    at node_modules\nogit\node_modules\git-node\nod
e_modules\git-net\smart-http.js:191:19
    at read (node_modules\nogit\node_modules\git-no
de\node_modules\git-net\node_modules\push-to-pull\transform.js:14:32)
    at onRead (node_modules\nogit\node_modules\git-
node\node_modules\git-net\node_modules\push-to-pull\transform.js:31:14)
    at check (node_modules\nogit\node_modules\git-n
ode\node_modules\git-node-platform\stream.js:45:16)
    at IncomingMessage.<anonymous> (node_modules\no
git\node_modules\git-node\node_modules\git-node-platform\stream.js:28:5)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by Owemeone** [comment]
Seems to be node 0.12

**Comment by rosieks** [comment]
@Owemeone - could to elaborate. I think that I have the same error after upgrade to node.js 0.12

**Comment by Cybermaxs** [comment]
same for me
